### ISSUE TITLE
Testing the script, some errors found

### ISSUE THREAD

**Issue by WolfangAukang** [RPM-Outpost/libimobiledevice#1]
Hello,

I was testing your script, and there are some issues found while trying to compile. I didn't have Cython, nor automake nor libtool. So, on the dnf installation, it would be nice to make sure automake and libtool are installed. For Cython, I had to use PIP.

And (this is mostly aesthetic) this script must be installed as superuser, so it would be nice to check if the logged user has the privileges to do it.

The rest worked fine. I could mount my iPod Touch 5g :)

**Comment by TheElectronWill** [comment]
Thank you for reporting this! I will improve the script as soon as I'll have the time, probably next week.
